// File generated by FlutterFire CLI — do not edit manually.
// Project: zehouse-wftech | Package: com.wftech.zehouse
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Android (com.wftech.zehouse) ──────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcH95mXlmYc1k0bSPizSThx6qXWkel06o',
    appId: '1:123244791185:android:51f0c58842dd8bd19a4630',
    messagingSenderId: '123244791185',
    projectId: 'zehouse-wftech',
    storageBucket: 'zehouse-wftech.firebasestorage.app',
  );

  // ─── iOS (com.wftech.zehouse) ──────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcH95mXlmYc1k0bSPizSThx6qXWkel06o',
    appId: '1:123244791185:ios:2a4125cbd30a19069a4630',
    messagingSenderId: '123244791185',
    projectId: 'zehouse-wftech',
    storageBucket: 'zehouse-wftech.firebasestorage.app',
    iosClientId:
        '123244791185-580nm03989vvv53nf38qbl1bhpnusio3.apps.googleusercontent.com',
    iosBundleId: 'com.wftech.zehouse',
  );

  // ─── Web ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcH95mXlmYc1k0bSPizSThx6qXWkel06o',
    appId: '1:123244791185:web:cbd8299795fb5a5d9a4630',
    messagingSenderId: '123244791185',
    projectId: 'zehouse-wftech',
    storageBucket: 'zehouse-wftech.firebasestorage.app',
  );
}
